# Generated by Django 3.2.7 on 2022-06-09 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfs', '0002_alter_files_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='Books',
        ),
    ]
