# Generated by Django 3.2.7 on 2022-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_rename_files_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(max_length=2000, upload_to=''),
        ),
    ]
